{% set name = "glfw" %}
{% set version = "3.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5234f4f29473e9a06bc7847d8371858dd135d38466eeeaa652fdc9f8f9ff0c20
  patches:
    # Mostly taken from
    # https://github.com/glfw/glfw/issues/2139
    # To enable compilation with older libc
    - patches_for_conda_forge.patch

build:
  number: 0
  # https://abi-laboratory.pro/index.php?view=timeline&l=glfw
  run_exports:
    - {{ pin_subpackage('glfw', max_pin='x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cmake
    - pkg-config  # [unix]
    - ninja  # [win]
    - make  # [unix]
  host:
    - xorg-libx11 {{ xorg_libx11 }}  # [linux]
    - xorg-libxrandr {{ xorg_libxrandr }}  # [linux]
    - xorg-libxinerama {{ xorg_libxinerama }}  # [linux]
    - xorg-libxcursor {{ xorg_libxcursor }}  # [linux]
    - xorg-libxi {{ xorg_libxi }}  # [linux]
    - libxkbcommon {{ libxkbcommon }}  # [linux]
    - wayland {{ wayland }}  # [linux]

test:
  commands:
    - test -f $PREFIX/lib/libglfw${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%/Library/lib/glfw3dll.lib exit 1  # [win]
    - if not exist %PREFIX%/Library/bin/glfw3.dll exit 1  # [win]

about:
  home: https://www.glfw.org/
  license: Zlib
  license_family: OTHER
  license_file: LICENSE.md
  summary: Open Source, multi-platform library for OpenGL, OpenGL ES and Vulkan application development.
  description: |
    GLFW is an Open Source, multi-platform library for OpenGL, OpenGL ES and
    Vulkan application development. It provides a simple,
    platform-independent API for creating windows, contexts and surfaces,
    reading input, handling events, etc.
  doc_url: https://www.glfw.org/documentation.html
  dev_url: https://github.com/glfw/glfw

extra:
  recipe-maintainers:
    - hmaarrfk
    - kmuehlbauer
    - hoechenberger
    - ryanvolz
    - traversaro
