travis:
  secure:
    BINSTAR_TOKEN: COEQc6ngHVzA1MTq4MJyNhv4quggyMmEt5v1wQOMi/doGbbnZXL9sZkgv7ypgyFu5pP+8KzVEHHDbL5kQHEjSxlUoK017rh7LD/uvCd7PSKhszjgNQCKMc89XvmWqJyieCtibCho1nqwOhHm1QH/yuoTtKJyOC5rnKME+uCyilZlBjZOcO792e1AbCHhzD2ZI0HIShZPrAvLvXIXV7jvbUYVCpsARYKnpdL1Wpii3iJW4HpgxFWzsRnEgzutWDzxhvEFHHp7E2kt/dchuxqPPrYe1fgDDn4D4e2XX0d4vJ9IioQEe60+XiyPXjK3O1Ic0Kcixo9QSDn2rfoQQqC5ZmmuuvDbOfQGX9Y2JUG0DkW5SfnSf+4ri5Z3+apWFmNGaA6rDFh3M+HXfhLk8mLCT/Fmwi7HmaVYlR1Oa0xCPIffqW9R9oxXuibNciJqqStwPlt5BBC9jE+WqPEiZUwZYubWZBetr0rMX+tNrTgOYHNjMi9kOIwKWALfvisKu2J7dvMgU8yBs83x8z+7xJlF+hRpXNKlaegWbJKMR2fyXYq4z+urGBmrFTtACccU6kUWvCyWdGcjX8AVKEmquQeuvZY2r8VEK+fk3W3e/3u4gCJ3bjR8cCLiNlfoZ3RErlDplrccAwMIYZdMiToRpwvklJbfNqi8t6k8Ojt2t4xmo4U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
