travis:
  secure:
    BINSTAR_TOKEN: jLpdq72cy3jDiP9e2v0n9JW1R/7wWZeNPq263WitOaSu219zpBW7Ah58q4Ue4+i/CwzUXIgpk5vrXpFbAFdhn2uEU+0hsuwUTXExGx99yYaa2kSd0G4yjJldCVx4ADeEMRBwOtUlfUXHSiLjETmM7Fdmnyg29AvSaFLpeZ3o12APS++bXtgP6UyRhhgG752p8DFgoXkNKGmhOqcopuz7IakJiHp12263dpyeeFOxjiSj/VgfrZL8mwl5al+xBgepd1JFOsz6NsrylRe/nOriY+DBiWBbONRqSZHTMBWGIujtzqkUQZ7QK+IjBV8aIvEuLOL4rWW/zpUCRoRYLM1vQ+uangTi6OwklqZ08qw7sueaSc/Yq6xZIZf3WQgNOoHdOguufxdz/4lwfLPdzxKPaVCqIj/RmUVONaHiEdjHb/w9vI9p3DHuXIWSGN4zgvfHaWMjhZ7F1r6ZMleqTW6wkwtOPXPt/ynbjYZEhf33R3U/RzGp9kF+OUv4tdf88j/33E4S8x0GAKVYNcGiGE+KDauYTqPPHs2tq1yOcEojibsk8zKNJQF264FfIAc6LwBcXE4a0ougLzNjpUfDZAoAfhscWEFKEm146yri44Sr8sJ2OiCXJcQMeF4AhTs0vRJxhnQxjfvrKIOBs0rxL46IiLqV9QFzBXWN6qP+F5zv4eA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
